[project]
name = "feather-log"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "birdnetlib>=0.18.0",
]

[dependency-groups]
dev = [
    "uv>=0.6.14",
]
